// New locations for DraftToDesign expansion: 16 cities + 12 sub-areas.
// Each entry: slug, cityName, state info, neighborhoods, blurb (city page),
// angleA + angleB (combo page local paragraphs).
export const LOCATIONS = [
  // ---------------- TEXAS ----------------
  {
    slug: 'arlington', cityName: 'Arlington', stateName: 'Texas', stateAbbr: 'TX', stateSlug: 'texas',
    neighborhoods: ['Entertainment District', 'Viridian', 'Dalworthington Gardens', 'North Arlington', 'Pantego', 'South Arlington'],
    blurb: `Sitting between Dallas and Fort Worth, Arlington blends mid-century ranch neighborhoods with fast-growing new developments. Homeowners here remodel to compete in a market shaped by the Entertainment District and two major sports stadiums.\n\nFrom game-day rental upgrades near AT&T Stadium to full-home remodels in Viridian, we deliver fast, affordable design work for Arlington projects of every size.`,
    angleA: `Arlington's housing stock is dominated by 1960s to 1980s brick ranch homes, which means most projects start with an existing-condition plan. We turn your measurements or sketches into clean, dimensioned drawings that contractors can bid from directly.`,
    angleB: `The rental market around the Entertainment District rewards owners who upgrade kitchens, bathrooms and curb appeal. A photorealistic render helps you test finishes before spending, and gives listing photos that stand out on game weekends.`,
  },
  {
    slug: 'plano', cityName: 'Plano', stateName: 'Texas', stateAbbr: 'TX', stateSlug: 'texas',
    neighborhoods: ['Legacy West', 'Willow Bend', 'Downtown Plano', 'Park Boulevard', 'Lakeside', 'Kings Ridge'],
    blurb: `Plano's corporate relocations turned it into one of the most competitive housing markets in Texas. New construction around Legacy West sits beside established neighborhoods where teardowns and luxury remodels are everyday business.\n\nWe help Plano homeowners, builders and investors move fast with professional floor plans, 3D renders and interior concepts delivered in days, not weeks.`,
    angleA: `In Plano's established neighborhoods, rising land values make teardowns and major additions common. Accurate as-built plans are the foundation: we document your existing home precisely so architects and builders can price the real scope.`,
    angleB: `Around Legacy West and the Tollway corridor, new luxury builds compete on finishes and presentation. Builders pre-sell with our exterior and interior renders months before completion, and buyers commit faster when they can see the finished home.`,
  },
  {
    slug: 'corpus-christi', cityName: 'Corpus Christi', stateName: 'Texas', stateAbbr: 'TX', stateSlug: 'texas',
    neighborhoods: ['South Side', 'Padre Island', 'Flour Bluff', 'Calallen', 'Portland', 'Downtown'],
    blurb: `Corpus Christi's Gulf Coast setting shapes everything about local design: coastal contemporary homes, beach houses on Padre Island, and remodels built to handle salt air and storm season.\n\nWe create floor plans, renders and exterior concepts tuned for coastal living, from hurricane-smart material choices to outdoor spaces made for the Texas coast.`,
    angleA: `Coastal homes in Corpus Christi face unique pressures: salt corrosion, humidity and hurricane exposure. Our exterior concepts specify coastal-appropriate materials and colors, and our renders show how your home will actually look in that bright Gulf light.`,
    angleB: `Padre Island's vacation rental market rewards properties with standout curb appeal and resort-style outdoor areas. A 3D exterior render lets you test pool decks, palapa covers and landscaping before committing to construction.`,
  },
  {
    slug: 'lubbock', cityName: 'Lubbock', stateName: 'Texas', stateAbbr: 'TX', stateSlug: 'texas',
    neighborhoods: ['Tech Terrace', 'South Lubbock', 'Lakeridge', 'West End', 'Buddy Holly District', 'Melrose'],
    blurb: `Lubbock's Texas Tech energy keeps its housing market moving: student rentals near campus, family homes in South Lubbock, and steady new construction on the west side.\n\nWe give Lubbock owners and investors professional design work at small-market prices, with the fast turnaround remote delivery makes possible.`,
    angleA: `Near Texas Tech, investors run student rentals where durable, low-maintenance design wins. Our space plans and interior concepts focus on layouts that rent well and finishes that survive turnover.`,
    angleB: `West Texas ranch and craftsman homes have great bones but dated interiors. A 3D interior render shows exactly how new flooring, paint and lighting transform these homes, so you spend with confidence.`,
  },
  {
    slug: 'irving', cityName: 'Irving', stateName: 'Texas', stateAbbr: 'TX', stateSlug: 'texas',
    neighborhoods: ['Las Colinas', 'Valley Ranch', 'Hackberry Creek', 'Downtown Irving', 'Cottonwood Valley'],
    blurb: `Irving's Las Colinas corridor is one of DFW's premier business addresses, surrounded by canal-side homes, golf-course communities and growing residential districts.\n\nWe serve Irving homeowners and builders with quick, professional plans and renders, from Las Colinas luxury updates to practical remodels across the city.`,
    angleA: `Las Colinas homes sit on canals and golf courses where exterior presentation matters. Our exterior design concepts and landscaping renders help owners upgrade curb appeal in a neighborhood where every home is on display.`,
    angleB: `Irving's central DFW location makes it a magnet for relocating professionals who buy quickly and remodel immediately. Remote delivery means your plans and renders arrive in days, keeping your project on a relocation timeline.`,
  },
  {
    slug: 'garland', cityName: 'Garland', stateName: 'Texas', stateAbbr: 'TX', stateSlug: 'texas',
    neighborhoods: ['Firewheel', 'Downtown Garland', 'Oakridge', 'Duck Creek', 'Centerville', 'Brentwood'],
    blurb: `Garland's 1950s to 1970s ranch neighborhoods are prime remodel territory: solid construction, great lots, and interiors ready for updating. Firewheel's growth keeps pushing values up.\n\nWe help Garland homeowners modernize affordably with accurate floor plans, kitchen and bath concepts, and renders that show the finished result before demolition starts.`,
    angleA: `Garland's mid-century ranch homes share similar footprints, which makes smart space planning especially valuable. We rework galley kitchens, closed-off living rooms and dated baths into open, modern layouts on paper first.`,
    angleB: `With DART rail access and relative affordability, Garland attracts first-time buyers who remodel in phases. Our phased plan sets show what to do now versus later, so every dollar lands where it counts most.`,
  },
  // ---------------- TEXAS sub-areas ----------------
  {
    slug: 'katy', cityName: 'Katy', stateName: 'Texas', stateAbbr: 'TX', stateSlug: 'texas',
    neighborhoods: ['Cinco Ranch', 'Grand Lakes', 'Firethorne', 'Seven Meadows', 'Old Katy', 'Cross Creek Ranch'],
    blurb: `Katy is Houston's new-construction capital: master-planned communities like Cinco Ranch and Firethorne add thousands of homes a year. Families moving in want personalized plans and finishes, fast.\n\nWe work with Katy buyers and builders on pre-construction plans, interior selections shown in 3D, and backyard concepts for those famously large Texas lots.`,
    angleA: `In Katy's master-planned communities, buyers often purchase from builder plan options, then want custom changes. We redraw builder plans with your modifications and render the result, so you approve changes before the builder prices them.`,
    angleB: `Katy lots are generous, and outdoor living is a way of life here. Our backyard and pool concepts, shown as photorealistic renders, help you design the outdoor space your family will actually use.`,
  },
  {
    slug: 'the-woodlands', cityName: 'The Woodlands', stateName: 'Texas', stateAbbr: 'TX', stateSlug: 'texas',
    neighborhoods: ['Alden Bridge', "Cochran's Crossing", 'Sterling Ridge', "Grogan's Mill", 'Carlton Woods', 'Town Center'],
    blurb: `The Woodlands sets the standard for upscale suburban living: custom homes tucked into the pines, golf-course estates in Carlton Woods, and a design review process that rewards quality.\n\nWe deliver the high-end plans, renders and interior concepts Woodlands projects demand, with the polish to satisfy both owners and design committees.`,
    angleA: `The Woodlands' design standards mean exterior changes need to look intentional. Our exterior renders show committees and neighbors exactly what you propose, smoothing approvals for facelifts, additions and landscaping.`,
    angleB: `Luxury homes here deserve luxury presentation. Interior design concepts with photorealistic 3D renders let you finalize stone, wood and lighting selections before ordering, avoiding five-figure mistakes.`,
  },
  {
    slug: 'sugar-land', cityName: 'Sugar Land', stateName: 'Texas', stateAbbr: 'TX', stateSlug: 'texas',
    neighborhoods: ['First Colony', 'Telfair', 'Riverstone', 'Greatwood', 'New Territory', 'Imperial'],
    blurb: `Sugar Land's master-planned communities house some of Houston's most affluent families, in large homes that eventually need thoughtful updating.\n\nWe create interior concepts, kitchen and bath plans, and exterior refreshes for Sugar Land homes, tuned to the scale and style of First Colony, Telfair and Riverstone.`,
    angleA: `Sugar Land's 1990s and 2000s-era homes are entering their remodel window: heavy trim, compartmentalized kitchens, formal living rooms nobody uses. Our concepts open these floor plans up for modern family life.`,
    angleB: `With highly rated schools and strong values, Sugar Land owners invest confidently in their homes. A 3D render package lets you compare two or three design directions side by side before committing to one.`,
  },
  {
    slug: 'frisco', cityName: 'Frisco', stateName: 'Texas', stateAbbr: 'TX', stateSlug: 'texas',
    neighborhoods: ['Star District', 'Phillips Creek Ranch', 'Stonebriar', 'Newman Village', 'Richwoods', 'Lexington Country'],
    blurb: `Frisco grew from small town to boomtown in two decades, with The Star, PGA headquarters and billions in development. New luxury construction dominates, and presentation sells.\n\nWe partner with Frisco builders and buyers on pre-sale renders, model-home interiors and custom plan changes, delivered at the speed this market demands.`,
    angleA: `Frisco builders compete on emotion: buyers fall in love with a vision. Our exterior and interior renders give builders marketing visuals that pre-sell homes before framing is finished.`,
    angleB: `In Phillips Creek Ranch and Newman Village, custom touches differentiate one luxury build from the next. We render your specific selections, from stair railings to outdoor kitchens, so the finished home matches the dream.`,
  },
  {
    slug: 'round-rock', cityName: 'Round Rock', stateName: 'Texas', stateAbbr: 'TX', stateSlug: 'texas',
    neighborhoods: ['Teravista', 'Brushy Creek', 'Forest Creek', 'Old Town', 'Paloma Lake', 'Behrens Ranch'],
    blurb: `Round Rock pairs Dell-driven employment with family-friendly suburbs and relentless new construction. First-time buyers and growing families remodel and expand here every day.\n\nWe give Round Rock homeowners fast, affordable plans and renders, from Teravista kitchen updates to Brushy Creek additions.`,
    angleA: `Round Rock's newer tract homes are well built but generic. Our interior concepts add personality: accent walls, lighting plans and finish palettes shown in 3D, so your home stops looking like the model next door.`,
    angleB: `Growing families in Forest Creek and Brushy Creek add bedrooms and living space as kids grow. Our addition plans document the existing home and design the expansion as one clean, buildable set.`,
  },
  // ---------------- CALIFORNIA ----------------
  {
    slug: 'anaheim', cityName: 'Anaheim', stateName: 'California', stateAbbr: 'CA', stateSlug: 'california',
    neighborhoods: ['Anaheim Hills', 'Downtown Anaheim', 'Platinum Triangle', 'Colony District', 'West Anaheim'],
    blurb: `Anaheim spans 1950s tract neighborhoods, the revitalized Colony District and hillside estates in Anaheim Hills. California's ADU boom hits especially hard here, where lot values reward smart additions.\n\nWe design ADUs, remodels and exterior updates for Anaheim properties, with plans and renders that make the most of every square foot.`,
    angleA: `Anaheim's post-war tract homes on generous lots are ideal ADU candidates. We design garage conversions and detached ADUs with floor plans that maximize rent while respecting setbacks and privacy.`,
    angleB: `In Anaheim Hills, hillside homes need exterior concepts that handle slope, views and fire-wise landscaping. Our 3D exterior renders show how new facades, decks and planting work with the terrain.`,
  },
  {
    slug: 'bakersfield', cityName: 'Bakersfield', stateName: 'California', stateAbbr: 'CA', stateSlug: 'california',
    neighborhoods: ['Seven Oaks', 'Stockdale', 'Rosedale', 'Downtown', 'Northwest', 'Haggin Oaks'],
    blurb: `Bakersfield offers Central Valley affordability with steady growth: ranch-style homes on large lots, new construction in the northwest, and an oil-and-ag economy that keeps moving.\n\nWe bring big-city design quality to Bakersfield at remote prices, with plans and renders that respect value-focused budgets.`,
    angleA: `Bakersfield's large lots and ranch homes invite additions: extra bedrooms, covered patios, detached workshops. Our plans document the existing home and design the addition to look original, not bolted on.`,
    angleB: `Summer heat dominates design decisions here. Our exterior concepts prioritize shade structures, light-colored materials and drought-smart landscaping, shown in renders so you see the cooling effect visually.`,
  },
  {
    slug: 'riverside', cityName: 'Riverside', stateName: 'California', stateAbbr: 'CA', stateSlug: 'california',
    neighborhoods: ['Wood Streets', 'Canyon Crest', 'Orangecrest', 'Mission Grove', 'Downtown', 'Alessandro Heights'],
    blurb: `Riverside anchors the Inland Empire: historic neighborhoods like the Wood Streets, citrus heritage, and commuters who traded coastal prices for space.\n\nWe design for Riverside's mix of historic craftsman homes and newer tract communities, with ADU plans and remodel concepts that fit each era.`,
    angleA: `The Wood Streets' historic homes need sensitive updates: our drafting documents existing conditions carefully, and our interior concepts modernize kitchens and baths while honoring original woodwork and proportions.`,
    angleB: `In Orangecrest and Canyon Crest, families want more living space without moving. We design additions and covered California rooms that blend with the existing architecture, rendered so HOAs and owners approve with confidence.`,
  },
  {
    slug: 'stockton', cityName: 'Stockton', stateName: 'California', stateAbbr: 'CA', stateSlug: 'california',
    neighborhoods: ['Brookside', 'Lincoln Village', 'Weston Ranch', 'Miracle Mile', 'Downtown', 'Parkwoods'],
    blurb: `Stockton's affordability draws Bay Area commuters and investors, and its older housing stock is being refreshed block by block.\n\nWe help Stockton owners and investors renovate smart: accurate plans, cost-effective interior concepts and renders that show the after before the work begins.`,
    angleA: `Investors refreshing Stockton rentals need designs that look great and wear well. Our interior concepts specify durable finishes and layouts that photograph beautifully for listings.`,
    angleB: `Brookside and Lincoln Village waterfront homes deserve exterior concepts that play up the Delta setting. Our landscaping and facade renders show how modest budgets create standout curb appeal.`,
  },
  {
    slug: 'irvine', cityName: 'Irvine', stateName: 'California', stateAbbr: 'CA', stateSlug: 'california',
    neighborhoods: ['Woodbridge', 'Turtle Rock', 'Quail Hill', 'Portola Springs', 'University Park', 'Westpark'],
    blurb: `Irvine's master-planned villages run on HOA guidelines and architectural review: every exterior change needs professional presentation.\n\nWe produce the polished plans and renders Irvine HOAs expect, plus interior concepts for the city's modern tract homes, all delivered remotely and fast.`,
    angleA: `Irvine HOAs approve what they can visualize. Our exterior renders present paint schemes, landscaping and hardscape changes exactly as proposed, dramatically improving approval odds.`,
    angleB: `Inside, Irvine's open-plan tract homes are a blank canvas. Our 3D interior concepts test furniture layouts, accent walls and lighting before you buy, tuned to the clean modern aesthetic buyers here expect.`,
  },
  // ---------------- CALIFORNIA sub-areas ----------------
  {
    slug: 'pasadena', cityName: 'Pasadena', stateName: 'California', stateAbbr: 'CA', stateSlug: 'california',
    neighborhoods: ['Old Pasadena', 'Bungalow Heaven', 'San Rafael Hills', 'Madison Heights', 'Playhouse District'],
    blurb: `Pasadena's craftsman heritage, from Bungalow Heaven's landmark district to grand San Rafael Hills estates, demands design with historical respect.\n\nWe draft sensitive remodel plans and interior concepts for Pasadena homes, modernizing kitchens and baths while preserving the woodwork and proportions that make these houses special.`,
    angleA: `Bungalow Heaven's landmark status means exterior changes face real scrutiny. Our detailed existing-condition drawings and proposed elevations give preservation reviewers exactly what they need to say yes.`,
    angleB: `Pasadena buyers pay a premium for restored character. Our interior renders show how period-appropriate updates, like historically styled tile and lighting, lift value without erasing history.`,
  },
  {
    slug: 'long-beach', cityName: 'Long Beach', stateName: 'California', stateAbbr: 'CA', stateSlug: 'california',
    neighborhoods: ['Belmont Shore', 'Naples', 'Bixby Knolls', 'Alamitos Beach', 'Downtown', 'Wrigley'],
    blurb: `Long Beach mixes beach-city condos, Naples canal homes and historic craftsman neighborhoods, all within minutes of the sand.\n\nWe design for coastal small lots: ADUs, condo remodels and beach-cottage updates, with plans and renders tuned for seaside living.`,
    angleA: `In Belmont Shore and Naples, small lots mean every square foot must earn its keep. Our space plans squeeze home offices, guest space and storage from footprints that look impossible on paper.`,
    angleB: `Coastal air punishes the wrong materials. Our exterior concepts specify salt-tolerant finishes and show them in renders, so your beach home looks sharp for years, not months.`,
  },
  {
    slug: 'glendale', cityName: 'Glendale', stateName: 'California', stateAbbr: 'CA', stateSlug: 'california',
    neighborhoods: ['Rossmoyne', 'Verdugo Woodlands', 'Adams Hill', 'Chevy Chase', 'Downtown Glendale'],
    blurb: `Glendale's hillside homes capture views from the Verdugos to downtown LA, in styles from Spanish colonial to mid-century modern.\n\nWe create view-maximizing remodel plans, hillside-sensitive exterior concepts and interior designs for Glendale's diverse housing stock.`,
    angleA: `Hillside lots in the Verdugo Woodlands need plans that respect slope, drainage and view corridors. Our drafting documents the terrain relationship carefully so additions sit naturally on the hill.`,
    angleB: `Glendale's luxury market rewards presentation: our interior and exterior renders help sellers and builders show the view-driven lifestyle buyers pay for, from glass railings to sunset-facing terraces.`,
  },
  {
    slug: 'santa-ana', cityName: 'Santa Ana', stateName: 'California', stateAbbr: 'CA', stateSlug: 'california',
    neighborhoods: ['Floral Park', 'French Park', 'Downtown', 'South Coast Metro', 'West Floral Park'],
    blurb: `Santa Ana pairs historic districts like Floral Park with dense urban infill and one of Orange County's strongest ADU markets.\n\nWe design ADUs, duplex conversions and historic-sensitive remodels for Santa Ana properties, with the detailed plans the city wants to see.`,
    angleA: `Santa Ana's ADU market is driven by multigenerational families and rental income. We design detached ADUs and garage conversions that feel like real homes, not afterthoughts, with plans ready for permit review.`,
    angleB: `Floral Park's historic homes need updates that respect their era. Our interior concepts modernize kitchens and systems while keeping the vintage character buyers love, shown in renders before work starts.`,
  },
  // ---------------- FLORIDA ----------------
  {
    slug: 'st-petersburg', cityName: 'St. Petersburg', stateName: 'Florida', stateAbbr: 'FL', stateSlug: 'florida',
    neighborhoods: ['Old Northeast', 'Historic Kenwood', 'Snell Isle', 'Crescent Heights', 'Downtown', 'Shore Acres'],
    blurb: `St. Petersburg's arts-driven revival fills historic bungalows and mid-century homes with buyers who care about design. The Gulf is never far, and hurricane season shapes every exterior decision.\n\nWe design storm-smart, beautiful updates for St. Pete homes: impact-ready exterior concepts, bungalow remodels and condo interiors.`,
    angleA: `Old Northeast and Historic Kenwood bungalows need updates that honor their character while hardening for storms. Our plans and exterior renders show impact windows, new roofs and refreshed facades as one cohesive design.`,
    angleB: `Downtown St. Pete's condo market moves on presentation. Our 3D interior renders help sellers and stagers show a unit's potential, turning vacant boxes into listings buyers can picture living in.`,
  },
  {
    slug: 'tallahassee', cityName: 'Tallahassee', stateName: 'Florida', stateAbbr: 'FL', stateSlug: 'florida',
    neighborhoods: ['Killearn', 'Southwood', 'Midtown', 'Betton Hills', 'Frenchtown', 'Buck Lake'],
    blurb: `Tallahassee's capital-city stability and two universities create constant housing demand: student rentals, state-worker family homes and Southern traditional estates under the oaks.\n\nWe serve Tallahassee owners and investors with practical, cost-effective plans and renders, from Killearn remodels to student-housing refreshes.`,
    angleA: `Student rentals near FSU and FAMU compete on photos. Our interior concepts specify durable, photogenic finishes, and our renders show owners the result before spending on turnover renovations.`,
    angleB: `Southwood and Killearn's traditional homes suit classic Southern updates: our exterior concepts refresh brick facades and landscaping with the timeless curb appeal this market rewards.`,
  },
  {
    slug: 'cape-coral', cityName: 'Cape Coral', stateName: 'Florida', stateAbbr: 'FL', stateSlug: 'florida',
    neighborhoods: ['Pelican', 'Cape Harbour', 'Tarpon Point', 'Sandoval', 'Diplomat', 'Burnt Store'],
    blurb: `Cape Coral's 400 miles of canals make it a waterfront city like no other: Gulf-access homes where the backyard is a dock and the pool is the living room.\n\nWe design pool-centric outdoor concepts, waterfront facelifts and interior updates for Cape Coral homes, rendered to show the Florida lifestyle buyers expect.`,
    angleA: `In Cape Coral, outdoor living sells the home. Our 3D backyard renders design pool decks, summer kitchens and lanai layouts that turn canal-front lots into resort-style retreats.`,
    angleB: `Snowbird buyers shop from photos before ever visiting. Our exterior and interior renders give Cape Coral sellers marketing visuals that capture northern buyers scrolling listings in winter.`,
  },
  {
    slug: 'port-st-lucie', cityName: 'Port St. Lucie', stateName: 'Florida', stateAbbr: 'FL', stateSlug: 'florida',
    neighborhoods: ['Tradition', 'St. Lucie West', 'Torino', 'PGA Village', 'Becker Ridge', 'Riverland'],
    blurb: `Port St. Lucie ranks among America's fastest-growing cities, with the master-planned Tradition community leading a Treasure Coast construction boom.\n\nWe support Port St. Lucie buyers and builders with pre-construction plans, interior selection renders and landscaping concepts for new homes.`,
    angleA: `Tradition's new builds move fast, and buyers want personalization before closing. We redraw builder plans with your changes and render the finished rooms, so upgrades are approved with confidence.`,
    angleB: `New-construction landscaping is often an afterthought. Our landscape concepts design the front and back yards as finished outdoor rooms, shown in renders that help new owners plan from day one.`,
  },
  {
    slug: 'hialeah', cityName: 'Hialeah', stateName: 'Florida', stateAbbr: 'FL', stateSlug: 'florida',
    neighborhoods: ['Palm Springs North', 'Country Club', 'West Hialeah', 'East Hialeah', 'Palm Springs'],
    blurb: `Hialeah's vibrant Cuban-American community fills multigenerational homes where additions and conversions make extended family life work.\n\nWe design practical additions, garage conversions and interior reconfigurations for Hialeah homes, maximizing space on modest lots.`,
    angleA: `Multigenerational living drives Hialeah's addition market: extra bedrooms, separate entrances, converted garages. Our plans design these for privacy and flow, so three generations live comfortably under one roof.`,
    angleB: `Hialeah's concrete-block homes are solid candidates for second-story additions. Our 3D exterior renders show how the expanded home looks from the street, keeping neighborhood character intact.`,
  },
  // ---------------- FLORIDA sub-areas ----------------
  {
    slug: 'coral-gables', cityName: 'Coral Gables', stateName: 'Florida', stateAbbr: 'FL', stateSlug: 'florida',
    neighborhoods: ['Gables by the Sea', 'Cocoplum', 'Miracle Mile', 'Old Cutler', 'Tahiti Beach', 'French Normandy Village'],
    blurb: `Coral Gables, the "City Beautiful," guards its Mediterranean Revival heritage with strict architectural review, and its estates set South Florida's luxury standard.\n\nWe produce the refined plans, luxury interior concepts and presentation renders that Coral Gables projects and review boards expect.`,
    angleA: `Coral Gables' review boards approve what they can see. Our photorealistic exterior renders present proposed changes with Mediterranean authenticity, from barrel tile to coral stone, improving approval odds.`,
    angleB: `Luxury buyers here expect turnkey perfection. Our interior design concepts with 3D renders let estate owners finalize every finish, fixture and furnishing before a single order is placed.`,
  },
  {
    slug: 'doral', cityName: 'Doral', stateName: 'Florida', stateAbbr: 'FL', stateSlug: 'florida',
    neighborhoods: ['Doral Isles', 'Costa Del Sol', 'Downtown Doral', 'Grand Bay', 'Doral Park', 'Provincial'],
    blurb: `Doral's master-planned golf communities and modern condos house Miami's international professional class in contemporary comfort.\n\nWe design modern interiors, condo remodels and outdoor concepts for Doral homes, with the clean, current aesthetic this market demands.`,
    angleA: `Doral's golf-course condos and townhomes compete on modern finishes. Our interior concepts deliver the sleek, light-filled look buyers expect, rendered from your actual floor plan.`,
    angleB: `In communities like Doral Isles, backyard upgrades, summer kitchens and pool decks, define the lifestyle. Our 3D outdoor renders design these spaces as extensions of the home.`,
  },
  {
    slug: 'clearwater', cityName: 'Clearwater', stateName: 'Florida', stateAbbr: 'FL', stateSlug: 'florida',
    neighborhoods: ['Island Estates', 'Countryside', 'Clearwater Beach', 'Harbor Oaks', 'Skycrest', 'Del Oro Groves'],
    blurb: `Clearwater's world-famous beach drives a tourism and vacation-rental economy where design directly affects income.\n\nWe create rental-optimized interiors, beach-condo remodels and coastal exterior concepts for Clearwater properties, designed to photograph beautifully and wear well.`,
    angleA: `Clearwater Beach vacation rentals live or die by listing photos. Our interior concepts specify coastal contemporary finishes that photograph bright and clean, and our renders show owners the result before renovation.`,
    angleB: `Countryside and Island Estates homes benefit from Florida indoor-outdoor updates: our concepts open living areas to lanais and pools, rendered so owners see the resort feel before construction.`,
  },
];
